### ISSUE TITLE
Addition of "held down" actions?

### ISSUE THREAD

**Issue by kdkrutil** [rohankapoorcom/homeassistant-config#58]
Hey there!

Your blueprint is working phenomenally so far and I'm super happy with it. Would it be possible for you to add the actions of holding down the paddles/button?

Bonus, totally unrelated question: Are you aware of any way to configure the notification LEDs through Home Assistant yet? I haven't seen anything for that part yet.

**Comment by rohankapoorcom** [comment]
Hey @kdkrutil - Which blueprint are you using that is missing the hold down actions? (Red or Blue and specific version would be helpful)

**Comment by kdkrutil** [comment]
Hy there, @rohankapoorcom. The blueprint I'm using is for the Red VZW31-SN.

**Comment by ss1225dev** [comment]
@rohankapoorcom hoping to see held down actions on the config button as well in the blue config!

**Comment by rohankapoorcom** [comment]
Sorry for the long delay on this @kdkrutil / @ss1225dev. I don't use held down actions and forgot about this :)

I just added support in #63 for the Red series. I'll update the blue series shortly before merging.

**Comment by rohankapoorcom** [comment]
Changes merged in. Please update your blueprints and you should see the new fields/actions!
