### ISSUE TITLE
Inovelli-vzm31-sn-blue-series-switch 

### ISSUE THREAD

**Issue by Motya-HA** [rohankapoorcom/homeassistant-config#62]
Inovelli-vzm31-sn-blue-series-switch blueprint stoped working for some reason

**Comment by rohankapoorcom** [comment]
@Motya-HA - It's still working for me. What version of Home Assistant and Zigbee2MQTT are you running?

**Comment by Motya-HA** [comment]
Wow...that was a long time ago. Let me check

**Comment by Motya-HA** [comment]
Looks like it works again

**Comment by rohankapoorcom** [comment]
Awesome! Glad to hear it.
